name: Central PR Scanner (CodeQL & Sonar)

on:
  workflow_dispatch:
    inputs:
      projectUrl:
        description: 'Target Repository URL (e.g., https://github.com/pjalbrz16/blade-runner-server.git)'
        required: true
        type: string
      prId:
        description: 'Pull Request ID to analyze'
        required: true
        type: string
      backendUrl:
        description: 'URL of the Java Backend'
        required: true
        type: string

jobs:
  analyze:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Worker Repo
        uses: actions/checkout@v4

      - name: Checkout Target PR & Generate CSV
        run: |
          git clone ${{ inputs.projectUrl }} target-repo
          cd target-repo
          
          # Fetch the specific PR branch and the default branch to find the diff
          
          DEFAULT_BRANCH=$(git branch --show-current)
          git fetch origin pull/${{ inputs.prId }}/head:pr-branch
          git checkout pr-branch
          
          # Find the impacted files and save them to a text file in the parent directory
          echo "change_type,file_path" > ../impacted_files.csv
          git diff --name-only origin/$DEFAULT_BRANCH...pr-branch >> ../impacted_files.csv
          git diff -U0 origin/$DEFAULT_BRANCH...pr-branch > ../pr_diff.txt
          echo "Impacted files CSV generated:"
          cat ../impacted_files.csv

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven' # Speeds up your build by caching dependencies!

      - name: Initialize CodeQL
        id: init
        uses: github/codeql-action/init@v3
        with:
          languages: java
          source-root: ./target-repo

#      - name: Autobuild Project
#        uses: github/codeql-action/autobuild@v3
#        env:
#          # Tell autobuild where the code is
#          GITHUB_WORKSPACE: ${{ github.workspace }}/target-repo

      - name: Build Project
        working-directory: ./target-repo
        run: mvn clean install -DskipTests

      - name: Run SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          projectBaseDir: ./target-repo
          args: >
            -Dsonar.projectKey=pjalbrz16_github-worker-action
            -Dsonar.organization=pjalbrz16
            -Dsonar.java.binaries=.

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v3
        with:
          category: "/language:java"
          upload: false
          upload-database: false
          output: codeql-results

      - name: Generate Call Graph CSV (Custom Query)
        env:
          CODEQL_DB_PATH: "${{ runner.temp }}/codeql_databases/java"
          CODEQL_CLI: "${{ steps.init.outputs.codeql-path }}"
        run : .github/scripts/generate_call_graph.sh


      - name: Webhook to Java Backend
        run: |          
          curl -v -X POST "${{ inputs.backendUrl }}/metrics" \
               -H "Authorization: Bearer ${{ secrets.BACKEND_TOKEN }}" \
               -F "prId=${{ inputs.prId }}" \
               -F "projectUrl=${{ inputs.projectUrl }}" \
               -F "sarifFile=@codeql-results/java.sarif" \
               -F "impactedFiles=@impacted_files.csv" \
               -F "callGraphCsv=@call_graph.csv" \
#               -F "fullCallGraph=@full_call_graph.csv"